// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  '/dash-board',
  '/login',
  '/routes',
];

class Routes {
  const Routes._();

  /// '控制台'
  ///
  /// [name] : '/dash-board'
  ///
  /// [routeName] : '控制台'
  static const String dashBoard = '/dash-board';

  /// '登录页'
  ///
  /// [name] : '/login'
  ///
  /// [routeName] : '登录页'
  static const String login = '/login';

  /// '路由页'
  ///
  /// [name] : '/routes'
  ///
  /// [routeName] : '路由页'
  static const String routes = '/routes';
}
